from pathlib import Path

path = Path('physics9_week2_velocity_time_galileo.py')
text = path.read_text(encoding='utf-8')
old = '''        xt_group, xt = self.xt_axes(x_max=6, y_max=12, width=5.9, height=3.65)
        p0, p1, p2, p3 = xt.c2p(0, 2), xt.c2p(2, 8), xt.c2p(4, 8), xt.c2p(6, 4)
        xt_segments = VGroup(Line(p0, p1, color=BLACK_LINE, stroke_width=3.3), Line(p1, p2, color=MID_GRAY, stroke_width=3.3), Line(p2, p3, color=DARK_GRAY, stroke_width=3.3))
        xt_fig = VGroup(xt_group, xt_segments)
        xt_panel = self.figure_panel(xt_fig, width=6.7, height=4.75, title="GIVEN x–t", caption="Compute slope Δx/Δt for each segment.", title_size=31, caption_size=24)
        eqs = self.equation_stack([r"v_1=\\frac{8-2}{2-0}=+3\\,\\mathrm{m/s}", r"v_2=\\frac{8-8}{4-2}=0\\,\\mathrm{m/s}", r"v_3=\\frac{4-8}{6-4}=-2\\,\\mathrm{m/s}"], sizes=[33, 33, 33], buff=0.27, max_width=6.2, max_height=2.2)
        vt_group, vt = self.vt_axes(x_max=6, y_min=-3, y_max=4, width=5.8, height=3.55)
        vt_segments = VGroup(Line(vt.c2p(0, 3), vt.c2p(2, 3), color=BLACK_LINE, stroke_width=3.3), Line(vt.c2p(2, 0), vt.c2p(4, 0), color=MID_GRAY, stroke_width=3.3), Line(vt.c2p(4, -2), vt.c2p(6, -2), color=DARK_GRAY, stroke_width=3.3))
        vt_fig = VGroup(vt_group, vt_segments)
        vt_panel = self.figure_panel(vt_fig, width=6.7, height=4.75, title="RESULTING v–t", caption="Each x–t slope becomes one horizontal v–t level.", title_size=31, caption_size=24)
        top = VGroup(xt_panel.group, vt_panel.group).arrange(RIGHT, buff=0.40); self.fit(top, 13.6, 4.72); top.move_to(UP * 0.02)
        eqs.to_edge(DOWN, buff=0.42); self.fit(eqs, 13.0, 1.55)
        self.assert_content_safe(VGroup(top, eqs), "problem 4")
'''
new = '''        xt_group, xt = self.xt_axes(x_max=6, y_max=12, width=5.75, height=3.55)
        p0, p1, p2, p3 = xt.c2p(0, 2), xt.c2p(2, 8), xt.c2p(4, 8), xt.c2p(6, 4)
        xt_segments = VGroup(Line(p0, p1, color=BLACK_LINE, stroke_width=3.3), Line(p1, p2, color=MID_GRAY, stroke_width=3.3), Line(p2, p3, color=DARK_GRAY, stroke_width=3.3))
        xt_fig = VGroup(xt_group, xt_segments)
        xt_panel = self.figure_panel(xt_fig, width=6.75, height=5.05, title="GIVEN x–t", caption="Compute slope Δx/Δt for each segment.", title_size=31, caption_size=24)
        eqs = self.equation_stack([r"v_1=\\frac{8-2}{2-0}=+3\\,\\mathrm{m/s}", r"v_2=\\frac{8-8}{4-2}=0\\,\\mathrm{m/s}", r"v_3=\\frac{4-8}{6-4}=-2\\,\\mathrm{m/s}"], sizes=[31, 31, 31], buff=0.18, max_width=5.75, max_height=1.75)
        vt_group, vt = self.vt_axes(x_max=6, y_min=-3, y_max=4, width=5.35, height=2.30)
        vt_segments = VGroup(Line(vt.c2p(0, 3), vt.c2p(2, 3), color=BLACK_LINE, stroke_width=3.3), Line(vt.c2p(2, 0), vt.c2p(4, 0), color=MID_GRAY, stroke_width=3.3), Line(vt.c2p(4, -2), vt.c2p(6, -2), color=DARK_GRAY, stroke_width=3.3))
        vt_fig = VGroup(vt_group, vt_segments)
        vt_panel = self.figure_panel(vt_fig, width=6.05, height=2.95, title="RESULTING v–t", caption="Each x–t slope becomes one horizontal v–t level.", title_size=29, caption_size=22)
        right = VGroup(eqs, vt_panel.group).arrange(DOWN, buff=0.28)
        layout = self.split_layout(xt_panel.group, right, left_width=6.75, right_width=6.10, max_height=5.25, center_y=-0.48, gap=0.42)
        self.assert_content_safe(layout.group, "problem 4")
'''
count = text.count(old)
if count != 1:
    raise SystemExit(f'Expected exactly one Problem 4 layout block, found {count}.')
path.write_text(text.replace(old, new), encoding='utf-8')
print('Applied Problem 4 layout V2 exactly once.')
